name: Release on GitHub


## Run only when we push a tag.
on:
  push:
    tags:
      - "v*"


jobs:

  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        # Don't run any test, as build should had already been verified (and it takes hours...)
        run: mvn clean verify -DskipTests
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "See release notes at [release_notes.md](https://github.com/WebFuzzing/Commons/blob/master/release_notes.md)."
          prerelease: false
          draft: false
          fail_on_unmatched_files: true
          files: |
            src/main/resources/wfc/schemas/report.yaml
            src/main/resources/wfc/schemas/auth.yaml
            src/main/resources/wfc/faults/fault_categories.json
